### ISSUE TITLE
Class that inherits from IEnumerable

### ISSUE THREAD

**Issue by mr-at0s** [mfidemraizer/trackerdog#42]
I would like to track changes of a class that inherits from IEnumerable. I made a minimal example (Keep in mind, the actual class is completely different). But essentially I get an ```System.InvalidOperationException```.

Example code:
```
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;
using TrackerDog;

namespace TrackerDogTestMin
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-us");
            var config = ObjectChangeTracking.CreateConfiguration()
                .TrackThisType<AList>()
                .TrackThisType<AWrapper>()
                .TrackThisType<IEnumerable<A>>()
                .TrackThisType<A>()
                .TrackThisType<IList<A>>()
                .TrackThisType<List<A>>();
            var trackableObjectFactory = config.CreateTrackableObjectFactory();

            var wrapperProxy = trackableObjectFactory.CreateFrom(new AWrapper());

            var changeTracker = wrapperProxy.GetChangeTracker();
            changeTracker.Changed += (sender, e) => { Console.WriteLine("Changed!"); };
            wrapperProxy.AList.AddSomeStrings();

            wrapperProxy.UndoChanges();
        }
    }

    public class AWrapper
    {
        public virtual AList AList { get; set; } = new AList();
    }

    public class AList : IEnumerable<A>
    {
        public virtual IList<A> TheActualList { get; set; } = new List<A>();

        public IEnumerator<A> GetEnumerator()
        {
            return TheActualList.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void AddSomeStrings()
        {
            TheActualList.Add(new A {Number = 1});
            TheActualList.Add(new A {Number = 2});
        }
    }

    public class A
    {
        public virtual int Number { get; set; }
    }
}
```

Exception:
```

System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no elements
  Source=System.Core
  StackTrace:
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source) in C:\Users\user\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\C37C6F15-3581-4F8C-99B2-44BE77015445\a1\223e5c27\Enumerable.cs:line 1593
   at TrackerDog.TrackableObjectFactoryInternal.CreateForCollection(Object some, IChangeTrackableObject parentObject, PropertyInfo parentObjectProperty) in C:\Users\user\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\B1F0BF37-70BB-4610-8DED-7C663E33A2F2\64\edb7fa8e\TrackableObjectFactoryInternal.cs:line 130
   at TrackerDog.Mixins.ChangeTrackableObjectMixin.ToTrackableCollection(PropertyInfo property, IChangeTrackableObject parentObject) in C:\Users\user\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\B1F0BF37-70BB-4610-8DED-7C663E33A2F2\b6\82d00e1e\ChangeTrackableObjectMixin.cs:line 56
   at TrackerDog.Mixins.ChangeTrackableObjectMixin.StartTracking(IChangeTrackableObject trackableObject, ObjectChangeTracker currentTracker) in C:\Users\user\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\B1F0BF37-70BB-4610-8DED-7C663E33A2F2\b6\82d00e1e\ChangeTrackableObjectMixin.cs:line 91
   at Castle.Proxies.AWrapperProxy.StartTracking(IChangeTrackableObject trackableObject, ObjectChangeTracker currentTracker)
   at TrackerDog.TrackableObjectFactoryInternal.Create(Object some, Type typeToTrack, ObjectChangeTracker reusedTracker, Object parentObject, PropertyInfo propertyToSet, Object[] constructorArguments) in C:\Users\user\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\B1F0BF37-70BB-4610-8DED-7C663E33A2F2\64\edb7fa8e\TrackableObjectFactoryInternal.cs:line 80
   at TrackerDog.TrackableObjectFactoryInternal.Create[TObject](TObject some, ObjectChangeTracker reusedTracker, Object parentObject, PropertyInfo propertyToSet, Object[] constructorArguments) in C:\Users\user\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\B1F0BF37-70BB-4610-8DED-7C663E33A2F2\64\edb7fa8e\TrackableObjectFactoryInternal.cs:line 107
   at TrackerDog.TrackableObjectFactoryInternal.CreateFrom[TObject](TObject some) in C:\Users\user\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\B1F0BF37-70BB-4610-8DED-7C663E33A2F2\64\edb7fa8e\TrackableObjectFactoryInternal.cs:line 167
   at TrackerDogTestMin.Program.Main(String[] args) in C:\DEV\properychangeproxy\properychangeproxy\TrackerDogTestMin\Program.cs:line 23



```

**Comment by mfidemraizer** [comment]
@mr-at0s hey! Thank you for using TrackerDog.

I believe that there should be no easy way to track changes from an enumerable which isn't a colleciton (i.e. `ICollection<T>`), because an enumerable can't be altered (it's just a *sequence*).

Why don't you implement `IList<A>` and you call `TheActualList` methods from them? So your class may be treated like a collection and enumerable, and you'll be able to track changes.

Let me know if I undestood your problem in the right way!

**Comment by mr-at0s** [comment]
Thanks for your reply. That makes sense! That works.

**Comment by mfidemraizer** [comment]
@mr-at0s You're welcome! ;)

If you find any other problem, feel free to fill as many issues you need and I'll try to give you solutions!
