### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by jkears** [mfidemraizer/trackerdog#52]
I created a simple test example in Net.Core 5.0 and TrackerDog 2.2.4 (full code below).  

I am getting an **"Access Denied"** exception when calling **CreateFrom** as follows;

`var typeA2 = trackableObjectFactory.CreateFrom(typeA);`

Test Project Console App

```
using System.Collections.Generic;
using System.Collections.Immutable;
using TrackerDog;
using TrackerDog.Configuration;

namespace DeltaTester
{
    class Program
    {

        public class TypeC
        {
            public string Name { get; set; }
        }

        public class TypeB
        {
            public string Name { get; set; }
            public TypeC TypeC { get; set; }
        }
       
        public class TypeA
        {
            public TypeA()
            {
                TypeBs = new List<TypeB>();
            }
            public string Name { get; set; }
            public List<TypeB> TypeBs { get; set; }
        }
        static void Main(string[] args)
        {

            IObjectChangeTrackingConfiguration config = ObjectChangeTracking.CreateConfiguration();
            config.TrackThisType<TypeA>();

            var typeA = new TypeA();

            typeA.Name = "test";

            ITrackableObjectFactory trackableObjectFactory = config.CreateTrackableObjectFactory();
            
            // after we rehydrate the changes
            var typeA2 = trackableObjectFactory.CreateFrom(typeA);

            typeA2.Name = "testa";
            typeA2.TypeBs.Add(new TypeB { Name = "b1", TypeC = new TypeC { Name = "c1" } });

            IObjectChangeTracker changeTracker = typeA2.GetChangeTracker();

            IImmutableSet<IObjectPropertyChangeTracking> changedProperties = changeTracker.ChangedProperties;

            // Also you can get unchanged properties
            IImmutableSet<IObjectPropertyChangeTracking> unchangedProperties = changeTracker.UnchangedProperties;


        }
    }
}
```

Stack Trace from exception;

>    at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
>    at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
>    at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.CreateType(TypeBuilder type)
>    at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.BuildType()
>    at Castle.DynamicProxy.Generators.ClassProxyWithTargetGenerator.GenerateType(String name, INamingScope namingScope)
>    at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
>    at Castle.DynamicProxy.Generators.ClassProxyWithTargetGenerator.GetGeneratedType()
>    at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyTypeWithTarget(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
>    at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyTypeWithTarget(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
>    at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyWithTarget(Type classToProxy, Type[] additionalInterfacesToProxy, Object target, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
>    at TrackerDog.TrackableObjectFactoryInternal.Create(Object some, Type typeToTrack, ObjectChangeTracker reusedTracker, Object parentObject, PropertyInfo propertyToSet, Object[] constructorArguments)
>    at TrackerDog.TrackableObjectFactoryInternal.Create[TObject](TObject some, ObjectChangeTracker reusedTracker, Object parentObject, PropertyInfo propertyToSet, Object[] constructorArguments)
>    at TrackerDog.TrackableObjectFactoryInternal.CreateFrom[TObject](TObject some)
>    at DeltaTester.Program.Main(String[] args) in C:\src\applications\DomainServices\DeltaTester\Program.cs:line 46

**Comment by jkears** [comment]
This is not an issue, I moved the classes outside of the program class
